language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
sudo:
    false
install:
  - pip uninstall -y setuptools
  - python bootstrap.py
  - sed -ir "s/SQLAlchemy.*/SQLAlchemy = ${SA_VERSION}/g" versions.cfg
  - ./bin/buildout -c base.cfg
env:
  - SA_VERSION=0.8.2
  - SA_VERSION=0.9.8
  - SA_VERSION=1.0.16
  - SA_VERSION=1.1.4
matrix:
  exclude:
    - python: 3.3
      env: SA_VERSION=0.8.2
    - python: 3.4
      env: SA_VERSION=0.8.2
    - python: 3.5
      env: SA_VERSION=0.8.2
before_script:
  - bin/flake8 --ignore=E,C901,F401,F821 --count src
script:
  - bin/coverage run bin/test -vv1
after_success:
  - pip install coveralls
  - coveralls
notifications:
    email: false
