---
jobs:
  - job: 'Test'
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      matrix:
        Python34:
          python.version: '3.4'
          sqla.version: '1.2.18'
        Python35:
          python.version: '3.5'
          sqla.version: '1.2.18'
        Python36:
          python.version: '3.6'
          sqla.version: '1.2.18'
        Python37-SA-1.1:
          python.version: '3.7'
          sqla.version: '1.1.15'
        Python37-SA-1.2:
          python.version: '3.7'
          sqla.version: '1.2.18'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: |
          python -m pip install --upgrade pip
          python bootstrap.py
          sed -ir 's/SQLAlchemy.*/SQLAlchemy = $(sqla.version)/g' versions.cfg
          bin/buildout -n -c base.cfg
        displayName: 'Install dependencies'

      - script: |
          bin/flake8
          JAVA_HOME=$JAVA_HOME_12_X64 bin/coverage run bin/test -vv1
        displayName: 'test'
