---
name: test

on:
  pull_request: ~
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'


jobs:
  test:
    name: "Test python-${{ matrix.python-version }}
     sqla: ${{ matrix.sqla-version }}
     CrateDB: ${{ matrix.crate-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        crate-version: [nightly]
        os: [ubuntu-latest]
        sqla-version: ['1.1.15', '1.2.18', '1.3.17']
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python bootstrap.py

          # replace SQLAlchemy version
          sed -ir 's/SQLAlchemy.*/SQLAlchemy = ${{ matrix.sqla-version }}/g' versions.cfg

          # replace CrateDB version
          if [ ${{ matrix.crate-version }} = "nightly" ]; then
            sed -ir 's/releases/releases\/nightly/g' base.cfg
            sed -ir 's/crate_server.*/crate_server = latest/g' versions.cfg
          else
            sed -ir 's/crate-/crate_/g' base.cfg
            sed -ir 's/crate_server.*/crate_server = ${{ matrix.crate-version }}/g' versions.cfg
          fi

          bin/buildout -n -c base.cfg

      - name: Test
        run: |
          bin/flake8
          JAVA_HOME=$JAVA_HOME_12_X64 bin/coverage run bin/test -vv1
